project:
  type: website

website:
  title: ""
  site-url: https://dacss.github.io/quarto_blog_template/
  twitter-card:
    creator: "@UMassDACSS"
    site: "@UMassDACSS"
  favicon: images/DACSS_Round_Network.png
  navbar:
    background: "#881c1c"
    logo: images/UMass White Wordmark Horiz.png
    right:
      - text: "August 2022 Posts"
        href: https://dacss.github.io/quarto_blog_template/
      - text: "Contributors"
        file: about.qmd
      - href: https://umass.edu/sbs/dacss
        text: "DACSS"
      - icon: github
        href: https://github.com/DACSS/quarto_blog_template
        aria-label: GitHub


format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true



